quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://127.0.0.1:3306/warehouse_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
quarkus.datasource.username=root
quarkus.datasource.password=${MYSQL_PASSWORD}
quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.packages=com.orlando.entity
