# 目录监听配置
# watch.group.series.path=
# watch.group.series.target-path=
# watch.group.series.single-episode-only=
# watch.group.movie.path=
# watch.group.movie.target-path=
# watch.group.movie.single-episode-only=

# 仅白名单命中的文件会进入处理队列（支持精确匹配或 `re:` 正则）
watch.allow-file-names=re:.*\.(m4v|mp4|mkv|ass|ssa|srt|vtt)$

# 输出文件命名模板
watch.filename.pattern={name}_s{snumber}.e{enumber}.{ext}
watch.filename.season-number-width=2
watch.filename.episode-number-width=2

# 按扩展名分流落库规则
watch.db.asset-file-extensions=mp4,mkv,m4v
watch.db.subtitle-file-extensions=ass,srt,ssa,vtt
